version: '3.3'

services:
  redis-1:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - curriculum-api-network

  curriculum-1:
    build: .

    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/static/
      - ./media:/app/media/
    env_file:
      - ./.env
    networks:
      - curriculum-api-network



networks:
  curriculum-api-network:
    external: true

volumes:
  static_value:

